config/routes.rb
Rails.application.routes.draw do

  root to: 'categories#index'

  resources :categories do
    resources :posts
  end

  resources :comments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, as: :source,dependent: :destroy
  validates_presence_of :name, :description
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :source, polymorphic: true
  validates_presence_of :author, :content

  validates :author, format: { with: /.[\s]./}

  def author=(s)
    write_attribute(:author, s.to_s.titleize)
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  has_many :comments, as: :source,dependent: :destroy

  has_attached_file :file
  do_not_validate_attachment_file_type :file
  validates_with AttachmentSizeValidator, attributes: :file, less_than: 2.megabytes
  validates_presence_of :name, :content

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]


  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @comment = Comment.new(source: @category)
    redirect_to category_posts_path(@category)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # GET /comments
  # GET /comments.json
  def index
  end

  def new
    @comment = Comment.new
    @comment.post = Post.find(params[:post_id])
  end

  # POST /comments
  # POST /comments.json
  def create

    @comment = Comment.new comment_params
    if @comment.save
      @new_comment = Comment.new
      respond_to do |format|
        format.html do
          flash[:success] = 'Your comment has been posted.'
          redirect_to @comment.source
        end
        format.js
      end
    else
      @new_comment = @comment
      respond_to do |format|
        format.html { render @comment.source }
        format.js { render action: 'failed_save' }
      end
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:author, :content, :source_type,:source_id)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @category = Category.find(params[:category_id])
    @comments = @category.comments
    @posts = @category.posts.order(created_at: :desc)
    @source = @category
    @comment = Comment.new(source: @source)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts.map{|upload| upload.to_jq_upload } }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new(source: @post)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.category_id = params[:category_id]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.category_id = params[:category_id]
    respond_to do |format|
      if @post.save
        format.html {
          redirect_to category_post_url(@post.category,@post) , notice: 'Post was successfully created.'
        }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to category_post_url(@post.category,@post), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to category_posts_url(@category), notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @category = Category.find(params[:category_id])
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :content, :category_id,:file)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/categories/_form.html.haml
= form_for @category, html: { class: "form form-horizontal category" } do |f|
  .form-group
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, class: 'form-control', required: true
      = f.error_span(:name)
  .form-group
    = f.label :description, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_area :description, class: 'form-control', required: true
      = f.error_span(:description)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), categories_path, :class => 'btn btn-default'

app/views/categories/edit.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/categories/index.html.haml
.page-header
  %h1
    Categories
    = link_to 'New category', new_category_path, :class => 'btn btn-primary'
.row
  - @categories.each do |category|
    .col-md-4
      .panel.panel-default.panel-body
        %h2=link_to category.name, category_path(category)
        %p= category.description.truncate(255)
        %div
          = link_to t('.show', :default => t("helpers.links.show")), category_path(category), :class => 'btn btn-default btn-xs'
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_category_path(category), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), category_path(category), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/categories/new.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/comments/_comment.html.haml
.panel.panel-default.panel-body
  = div_for comment, class: "#{comment}" do
    %h4.comment-author
      Author:
      = sanitize(comment.author)
    %p.comment-content
      Content:
      = sanitize(comment.content)
    %span.date
      %small
        Created:
        = time_ago_in_words(comment.created_at)
        ago

app/views/comments/_comment_form.html.haml
.panel.panel-default.panel-body
  = form_for [@comment], remote: true do |f|
    .form-group
      = f.label :author, class: 'control-label col-lg-2'
      .col-lg-10
        = f.text_field :author, class: 'form-control', required: true
        = f.error_span(:author)
        %br
    .form-group
      = f.label :content, class: 'control-label col-lg-2'
      .col-lg-10
        = f.text_area :content, class: 'form-control', required: true
        = f.error_span(:content)
        = f.hidden_field :source_id, value: @comment.source_id
        = f.hidden_field :source_type, value: @comment.source_type
    .form-group
      .col-lg-offset-2.col-lg-10
        = f.submit nil,class: 'btn btn-primary'
        = tag "input", {  "type" => "button", "value" => "Cancel", "onclick" => "cancel()" }
    = render 'shared/error_messages', object: f.object
:javascript
  function cancel(){
  $("#comment-form").hide().val('');
  $("#show").show();
  };

app/views/comments/create.js.erb
var comments_list = $('#comments-list');
comments_list.append('<%= escape_javascript(render partial: @comment) %>');
comments_list.find('div:last-child').addClass('last-comment');
$('#comments-count').html('This article has <%= escape_javascript(pluralize(@comment.source.comments.count, 'comment')) %>');
$("#show").show();
$('#comment-form').val('').hide();

app/views/comments/failed_save.js.erb
$('#comment-form').html('<%= escape_javascript(render('comments/comment_form')) %>');

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title BlogAheront

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "BlogAheront", root_path, class: "navbar-brand"

    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{type: "button", data: {dismiss: "alert"} }
            %span{aria: {hidden: "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/posts/_form.html.haml
= form_for [@post.category, @post],  html: { class: "form form-horizontal post" } do |f|
  .form-group
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, class: 'form-control', required: true
    = f.error_span(:name)
  .form-group
    = f.label :content, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_area :content, class: 'form-control', required: true
    = f.error_span(:content)
  .form-group
    = f.label 'Add files...', class: 'control-label col-lg-2'
    .col-lg-10
      = f.file_field :file
      = f.error_span(:file)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), category_posts_path(@post.category), :class => 'btn btn-default'

app/views/posts/edit.html.haml
- model_class = Post
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/posts/index.html.haml
.page-header
  %h1= @category.name
  %p
    = @category.description
    = link_to 'New post', new_category_post_path(), :class => 'btn btn-primary'
%br
  .row
    - @posts.each do |post|
      .col-md-4
        .panel.panel-default.panel-body
          %h3
            = link_to post.name, category_post_path(@category,post)
          %p= post.content.truncate(255)
          - if post.file.present?
            %p= link_to post.file_file_name, post.file.url
          %br
          = link_to t('.show', :default => t("helpers.links.show")), category_post_path(post.category_id,post), :class => 'btn btn-default btn-xs'
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_category_post_path(post.category_id,post), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), category_post_path(post.category_id,post), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'
= tag "input", { "id" => "show", "type" => "button", "value" => "Add comment", "onclick" => "addComment()" }
%h4#comments-count
  This category has
  = pluralize(@category.comments.count, 'comment')
#comment-form
  =render 'comments/comment_form', locals: {source: @category}
#comments-list
  = render partial: @category.reload.comments.order(created_at: :desc)
:javascript
  $(document).onload(
  $("#comment-form").hide()
  );
  function addComment(){
  $("#comment-form").show()
  $("#comment-form.form-group").val('')
  $("#show").hide()
  };

app/views/posts/new.html.haml
- model_class = Post
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/posts/show.html.haml
- model_class = Post
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @post.name
%p
  %strong= model_class.human_attribute_name(:content) + ':'
  %br
  = @post.content
-if @post.file.present?
  %p
    = link_to @post.file_file_name, @post.file.url
= link_to t('.back', :default => t("helpers.links.back")), category_posts_path(@post.category_id), :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_category_post_path(@post.category_id,@post), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), category_post_path(@post.category_id,@post), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
= tag "input", { "id" => "show", "type" => "button", "value" => "Add comment", "onclick" => "addComment()" }
%h4#comments-count
  This article has
  = pluralize(@post.comments.count, 'comment')
#comment-form
  =render 'comments/comment_form',  locals: {comment: @comment}
#comments-list
  = render partial: @post.reload.comments.order(created_at: :desc)

:javascript
  $(document).onload(
  $("#comment-form").hide()
  );
  function addComment(){
  $("#comment-form").show();
  $("#comment-form.form-group").val('');
  $("#show").hide();
  };

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  %p
    This form has #{pluralize(object.errors.count, 'problem')}
  %ul
    - object.errors.full_messages.each do |msg|
      %li= msg